dfranx/SHADERed

UI/UIView.h
Base class should have a virtual destructor otherwise ```delete (UIView*) some_ptr;``` won't be able to call a derived destructor (even a default one).
=> [TRIVIAL] Mem-leak fix

UI/CreateItemUI.cpp
```
if (m_item.Data != nullptr)
delete m_item.Data;
```
m_item.Data:
https://github.com/dfranx/SHADERed/blob/24ba95faebfde61581a08792b82f5ad2cb13d69f/Objects/PipelineItem.h#L45
it leads to mem leak as 'delete' operator can't delete 'void*' proper. (not type information -> not size data, and no information about destructor, ... )
https://github.com/dfranx/SHADERed/blob/24ba95faebfde61581a08792b82f5ad2cb13d69f/Objects/PipelineItem.h#L45
i.e. destructors of internal fields (ex https://github.com/dfranx/SHADERed/blob/24ba95faebfde61581a08792b82f5ad2cb13d69f/Objects/PipelineItem.h#L78)  won't be executed.
=> Memory leak fix

Objects/ArcBallCamera.h
Fixed missed return ArcBallCamera '=' operator.
Details:
inline ArcBallCamera& operator=(const ArcBallCamera& arc)  - it should return ArcBallCamera& value so I've added 'return *this;' to fix it.
=> Fixed missed return ArcBallCamera '=' operator

CMakeLists.txt, Misc/Linux/io.github.dfranx.SHADERed.appdata.xml, Misc/Linux/io.github.dfranx.SHADERed.desktop
This also installs those files in CMake to expose SHADERed to the application launcher once installed.
=> Add XDG desktop and AppData files for Linux integration

.gitignore, CMakeLists.txt, README.md
The default behaviour when compiling with CMake is an in-source build, which mixes build artifacts with the source. I don't find this as a good way to compile the project. As such, I added support for out-of-source builds, which places the build artifacts in a separate. However, I still kept the binary output to the `bin/` directory. The default behaviour of performing in-source builds still works, as per my limited testing.
In conjunction with this support for out-of-source builds, I also updated the docs, primarily the `README.md` file.
=> Added Support for Out-of-Source Builds

CMakeLists.txt, README.md
This PR solves some issues when building the project on macOS. Following the instructions in README didn't work for at least versions below 10.15 (Catalina).
The CMake configuration now sets `CMAKE_CXX_STANDARD` to `17` to support C++17 features. This was previously ignored by CMake and/or compilers and would result in errors with unsupported features in previous C++ versions.
Due to changes in Mojave which [broke linking Homebrew libraries](https://stackoverflow.com/questions/54068035/linking-not-working-in-homebrews-cmake-since-mojave), the CMake configuration will now link the `/usr/local/lib` directory to make it possible to link Homebrew-installed libraries for macOS builds.
There's also now some extra information added to help solve issues with SDK target no being correct. This is …
=> Fix build configuration for macOS 10.14+

README.md
These installation methods make it easier for power users to install SHADERed quickly.
=> Add Scoop and Flatpak installation instructions to the README

Misc/Linux/org.shadered.SHADERed.appdata.xml
The AppStream specification requires recent releases to be put first (instead of last).
=> Fix release order in AppStream metadata

src/SHADERed/Engine/GLUtils.cpp
Related/fixes #73 (i think)
Amd gl outputs errors from `glgetShaderInfoLog` in a different format than what the previous implementation expected, which would cause a crash calling stoi on an invalid number string
Example amd output:
```
Vertex shader failed to compile with the following errors:
ERROR: 0:10: error(#132) Syntax error: "rawr" parse error
ERROR: error(#273) 1 compilation errors.  No code generated
```
This fixes crash to parse the second line correctly, the last line will be ignored, but im not sure if theres any value in it, this also may want to be tested on nvidia, but the code path should be the same as before in that case
=> glutils: fix glsl error parsing for amd

main.cpp
- Use `XDG_DATA_HOME` as that's the equivalent of `$HOME/.local/share`.
- Fix the path when using `XDG_DATA_HOME` (the full path should not contain `.local/share` again).
=> Fix XDG data paths

Misc/Linux/org.shadered.SHADERed.appdata.xml
This also adds releases that were previously missing in the release log.
=> Update AppStream metadata for 1.3.5

CMakeLists.txt
I was able to get this to compile under Ubuntu 18.04 (with `g++-8`).  `stdc++fs` needs to be a dependency or the linking will fail when using what's in <filesystem>
=> Add `stdc++fs` as a linking target for Linux

src/SHADERed/Objects/ProjectParser.cpp
This fixes two issues with the render state serialization at the cost of bigger footprint of disk (but I don't think that is avoidable to get correct behaviour).
The first issue is serializing of the depth test. If you turn off depth testing, save the project and then re-open it, it'll restore depth testing to on. This is because the default constructor of the `RenderState` object turns depth testing on and because the logic of the serialization is to only write depth test state info if depth testing was on.
The other issue is that, if you turn off blending, depth testing or stencil testing, you'll lose all customization on save. Same thing as the previous issue, the serialization only writes the individual setting if the overall feature is on. This isn't as big of an issue, but it would …
=> Fixed saving of render state

CMakeLists.txt
This silences a CMake warning about OpenGL when compiling on Linux: 
```
CMake Warning (dev) at /usr/share/cmake/Modules/FindOpenGL.cmake:305 (message):
Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
cmake_policy command to set the policy and suppress this warning.
FindOpenGL found both a legacy GL library:
OPENGL_gl_LIBRARY: /usr/lib64/libGL.so
and GLVND libraries for OpenGL and GLX:
OPENGL_opengl_LIBRARY: /usr/lib64/libOpenGL.so
OPENGL_glx_LIBRARY: /usr/lib64/libGLX.so
OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
CMakeLists.txt:131 (find_package)
This …
```
=> Use the GLVND OpenGL library on Linux by default

.gitignore, CMakeLists.txt
This PR fixes compilation on OSX Catalina. The issue was that some include directories were missing from `CMakeLists.txt`
=> Fix compilation on OSX Catalina

CMakeLists.txt
Giving a chance to everything that can render SVG, and keeping the PNGs as fallback.
=> Install SVG icon alongside the PNG ones

bin/data/shortcuts.kb, src/SHADERed/UI/PreviewUI.cpp
Added the 'previous' button (an exact counterpart of the 'forward' button), as well as a 'reset time' button to the preview UI controls, as well as keybinds for them.
I was extremely missing those and made them for myself, but then decided to quickly organize that into a PR.
The current ux is pretty weird, reset time is somewhere in the menus, there is a forward button but no backward button.
And I know that technically shaders should use time as a monotonic source and not care about the absolute value, but in my example my time uniform (that I do not control) always goes from 0 to 1, and I also wanted to precisely look at some frames (moving forward and backward) as well as look at how it looks in 60fps (so unbinding time uniform from time and pinning it does not always work), and I mean …
=> Add missing time control buttons to the preview UI

libs/misc/ImFileDialog.cpp, main.cpp, src/SHADERed/Engine/GLUtils.cpp, src/SHADERed/Engine/GeometryFactory.cpp, src/SHADERed/InterfaceManager.cpp, src/SHADERed/Objects/Debug/PixelInformation.h, src/SHADERed/Objects/Names.cpp, src/SHADERed/UI/CodeEditorUI.cpp, src/SHADERed/UI/Debug/VectorWatchUI.cpp, src/SHADERed/UI/PipelineUI.cpp, src/SHADERed/UI/PipelineUI.h, src/SHADERed/UI/PreviewUI.h, src/SHADERed/UI/Tools/DebuggerOutline.cpp
SHAREDed crashed when debugging a geometry shader with lines_adjacency input in a VertexBuffer.
+ fixed UI/DebugOutline for lines_adjacency
+ InterfaceManager.cpp, moved geometry code after tesselation
+ added a bunch of minor fixes after valgrind/memcheck session, in order to ease further debugging
=> fix crash when debugging GLSL geometry shader

libs/misc/dds.c
I attempted to load an uncompressed DDS volume, but part of the first few rows were missing. I've attached the .dds file I was using. I set the very first pixel to yellow so it was easy to see where it starts. GIMP can be used to view it.
[terrain-dds.zip](https://github.com/dfranx/SHADERed/files/6721134/terrain-dds.zip)
This patch seems to fix it. I'm not 100% sure how it all works, but I think the 128 bytes is the header mentioned here: https://docs.microsoft.com/en-us/windows/win32/direct3ddds/dds-file-layout-for-volume-textures
Perhaps your test image was coincidentally 32 pixels wide?
Screenshot of the bug:
Screenshot of the fixed version:
=> Fix uncompressed DDS volumes missing first few pixels

src/SHADERed/Objects/RenderEngine.cpp, src/SHADERed/Objects/RenderEngine.h, src/SHADERed/UI/CodeEditorUI.cpp
RenderEngine: added missing parameter `sedVarLoc`to DebugDrawPrimitives call.
other minor changes:
- RenderEngine: removed GetPixelID, use getPixelID instead
- fix CodeEditorUI::Open to parse GSSPV when geom is selected
=> fix 3D model debugging

src/SHADERed/Objects/PluginAPI/Plugin.h, src/SHADERed/Objects/PluginManager.cpp, src/SHADERed/Objects/PluginManager.h
This PR adds [`IPlugin3`](https://github.com/KevinGliewe/SHADERed/blob/5efeb121dd39f96218ab34d633193167c921c10f/src/SHADERed/Objects/PluginAPI/Plugin.h#L477-L484) witch gives plugins the possibility to register plugins themselves.
This functionality can be used to create runtime-plugins for different languages.
I created an [experimantal .NET 5 runtime plugin](https://github.com/KevinGliewe/SHADERedCLR) based on it.
Since you mentioned in your [Blog Post](https://shadered.org/blog?id=9) you plan to extend the plugin api anyway, i thought it would be a great opportunity to propose this addition as well.
* Addition of the type [`IPlugin3`](https://github.com/KevinGliewe/SHADERed/blob/5efeb121dd39f96218ab34d633193167c921c10f/src/SHADERed/Objects/PluginAPI/Plugin.h#L477-L484)
* Move a lot of …
=> Add IPlugin3 with RegisterPlugin

Misc/Linux/org.shadered.SHADERed.appdata.xml
This is required so that I can update the Flatpak to the latest version.
=> Update AppStream metadata for SHADERed 1.5.4
